appearance:
  theme_day: minimal
  theme_night: minimal
  font: minimal
  font_size: L

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Personal page of Xueming Fu'
    twitter: ''

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: false
    highlight_active_link: true

footer:
  copyright:
    notice: 'Â© {year} Xueming Fu. All rights reserved.'
    license:
      enable: true
      allow_derivatives: true
      share_alike: true
      allow_commercial: true

features:
  syntax_highlighter:
    enable: true
  math:
    enable: true
  privacy_pack:
    enable: false
  avatar:
    shape: circle
